% UQ_UQLINKOPTIONS display a helper for the main options needed to create a
%                 computational model through UQLink in UQLab.
%    UQ_UQLINKOPTIONS displays the main options needed by the command
%    <a href="matlab:help uq_createModel">uq_createModel</a> to create a MODEL object in UQLab 
%
%    See also: uq_createModel, uq_evalModel, uq_getModel, uq_listModels,
%              uq_selectModel 


disp('Quickstart guide to the UQLab UQLink Module')
disp('  ')
fprintf('In the UQLab software, UQLink MODEL objects are created by the command:\n')
fprintf('    myUQLinkModel = uq_createModel(UQLINKOPTIONS)\n');
fprintf('The options are specified in the UQLINKOPTIONS structure.\n')  

fprintf('\nExample: to create a UQLink object that connects UQLab to a third-party software \nwhose command line, for a given input file, reads ''myBeam BeamDeflection.inp'' \n(myBeam is an executable and BeamDeflection.inp is a configuration input file), type:\n')
fprintf('    UQLINKOPTIONS.Type = ''UQLink'';\n')
fprintf('    UQLINKOPTIONS.Command = ''myBeam BeamDeflection.inp'';\n')
fprintf('    UQLINKOPTIONS.Template = ''BeamDeflection.inp.tpl;\n')
fprintf('    UQLINKOPTIONS.Output.Parser = ''uq_readOutput'';\n')
fprintf('    UQLINKOPTIONS.Output.FileName = ''BeamDeflection.out'';\n')

fprintf('    myUQLinkModel = uq_createModel(UQLINKOPTIONS);\n')

fprintf('\nIn this example, it is assumed that:,\n')
fprintf('  - the template file is called ''BeamDeflection.inp.tpl'';\n')
fprintf('  - the output file generated by the third-party software is called ''BeamDeflection.out'';\n')
fprintf('  - the matlab file called ''uq_readOutput.m'' can be used to parse the output file.\n')

fprintf('\nTo evaluate the computational model associated to the UQLink object on a given point X, type:\n')
fprintf('    Y = uq_evalModel(X);\n')


fprintf('\nThe following options are set by default if not specified by the user:\n\n')
fprintf('    UQLINKOPTIONS.ExecutablePath = '' '' ; %%(the executable path is the current working directory)\n')
fprintf('    UQLINKOPTIONS.ExecutionPath = '' '' ;  %%(the execution path is the current working directory)\n')
fprintf('    UQLINKOPTIONS.Marker = {''<'',''X'',''>''} ;  \n')
fprintf('    UQLINKOPTIONS.Counter.Digits = 6 ;  \n')
fprintf('    UQLINKOPTIONS.Counter.Offset = 0 ;  \n')
fprintf('    UQLINKOPTIONS.Archiving.Action = ''save'' ;  \n')
fprintf('    UQLINKOPTIONS.Archiving.Zip = true ;  \n')

fprintf('\n')
fprintf('Please refer to the UQLink User Manual (<a href="matlab:uq_doc(''UQLink'',''html'')">HTML</a>,<a href="matlab:uq_doc(''UQLink'',''pdf'')">PDF</a>)');
fprintf('for more detailed\ninformation on the available features.')
fprintf('\n\n')