function Skeleton = uq_copula_skeleton()

Skeleton = struct('Type',[], ... % Generic fields
    'Dimension', [], ...
    'Parameters', [], ...
    'RankCorr', [], ...   % Fields specific to Gaussian and Independence copulas
    'cholR', [], ...
    'Family', [], ...     % Fields specific to Pair copula
    'Rotation', [], ...
    'Structure', [], ...  % Fields specific to Vine copulas
    'Families', [], ...   
    'Rotations', [], ...
    'Truncation', [], ...
    'Pairs', [], ...
    'CondVars', [], ...
    'Trees', [], ...
    'Variables',[]);
